### ISSUE TITLE
Strange vertical alignment

### ISSUE THREAD

**Issue by mglisse** [GUDHI/GUDHI.github.io#7]
https://github.com/GUDHI/GUDHI.github.io/blob/7b44cf74fd9c85de9d90e831bb112d7291b457fb/_sass/_06_typography.scss#L218

I believe this is responsible for (some of) the strange alignment we see on the website in pink boxes. I guess it tries to leave some space between consecutive definitions (which would explain why that doesn't apply to the first one), but that's just not working for us. A value of 0 looks way better.

**Comment by VincentRouvreau** [comment]
@mglisse you were right, it removes the white space over
Introduced in: | GUDHI 2.3.0
Copyright:       | MIT (GPL v3)
Requires:        | POT
